### ISSUE TITLE
`substrate-ingest` failed to process the block with `tip` as object type

### ISSUE THREAD

**Issue by ken-centrality** [subsquid/squid#108]
**Describe the bug**
This [line of code](https://github.com/subsquid/squid/blob/master/substrate-ingest/src/sink.ts#L266) throws error "Do not know how to serialize a BigInt" which originate from `pg` package. Turns out because the `tip` value is an object type `{tip: 0n, feeExchange: undefined}` instead of `0n`

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at prepareObject (/Users/ken/relayer-services/node_modules/pg/lib/utils.js:85:19)
    at prepareValue (/Users/ken/relayer-services/node_modules/pg/lib/utils.js:66:12)
    at arrayString (/Users/ken/relayer-services/node_modules/pg/lib/utils.js:29:31)
    at prepareValue (/Users/ken/relayer-services/node_modules/pg/lib/utils.js:63:12)
    at prepareValueWrapper (/Users/ken/relayer-services/node_modules/pg/lib/utils.js:193:12)
    at writeValues (/Users/ken/relayer-services/node_modules/pg-protocol/dist/serializer.js:67:41)
    at Object.bind (/Users/ken/relayer-services/node_modules/pg-protocol/dist/serializer.js:98:5)
    at Connection.bind (/Users/ken/relayer-services/node_modules/pg/lib/connection.js:160:26)
    at Query.prepare (/Users/ken/relayer-services/node_modules/pg/lib/query.js:211:18
```

**To Reproduce**
1. Run `substrate-ingest` against our testnet
```
yarn squid-substrate-ingest -e wss://nikau.centrality.me/public/ws --start-block 5001560 --out postgres://postgres:postgres@localhost:5432/nikau-archive --write-batch-size 1
```
2. The process will hang, to get the actual error, wrap this [block](https://github.com/subsquid/squid/blob/master/substrate-ingest/src/sink.ts#L264-L274) inside a `try...catch`

**Expected behavior**
- A warning about `tip` value is not in an expected type, but continue on rather getting stuck

**Environment (please complete the following information):**
 - @subsquid/substrate-ingest: v1.1.1
 - node.js: v18.2.0
 - npm: v8.9.0
 - OS: Mac v12.4

**Applicable to decoding issues:**
 - chain name: Nikau
 - block: 5001560
 - extrinsic: 2
 - endpoint: https://nikau.uncoverexplorer.com/extrinsic/5001560-2

**Comment by ken-centrality** [comment]
@belopash yip, submitted a PR, please review when you can :)

**Comment by eldargab** [comment]
Closed by https://github.com/subsquid/squid/commit/f24f8ed01d806dc9cb0adaee595acd13299d5381
