### ISSUE TITLE
Ingest fails on 🐍 block

### ISSUE THREAD

**Issue by lumir-mrkva** [subsquid/squid#75]
Ingest refuses to process this block https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbasilisk-rpc.dwellir.com#/explorer/query/0x6e27fe16eea91adfa509401cd2285714000af33c4b85741d2aafece45e1bce7e on Basilisk

with exception:
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
              (0, assert_1.default)(val != null, msg)
at assertNotNull (/squid/util/util-internal/lib/misc.js:18:26)
at CallParser.next (/squid/substrate-ingest/lib/parse/call.js:324:50)
at CallParser.find (/squid/substrate-ingest/lib/parse/call.js:300:30)
at CallParser.visitWrapper (/squid/substrate-ingest/lib/parse/call.js:271:27)
at CallParser.visitCall (/squid/substrate-ingest/lib/parse/call.js:183:22)
at CallParser.visitBatchItems (/squid/substrate-ingest/lib/parse/call.js:242:22)
at CallParser.visitBatchAll (/squid/substrate-ingest/lib/parse/call.js:208:14)
at CallParser.visitCall (/squid/substrate-ingest/lib/parse/call.js:168:22)
at CallParser.visitExtrinsic (/squid/substrate-ingest/lib/parse/call.js:134:22)
at new CallParser (/squid/substrate-ingest/lib/parse/call.js:124:18)
```

version:
```
subsquid/substrate-ingest:firesquid
sha256:2a7d82afbcddf394c87de1b456c76a1f465f571e2b646be0d8b58470229f5ba9
```

complete error:
``` 
{"level":5,"time":1657813904006,"ns":"sqd:substrate-ingest","err":{"generatedMessage":true,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"==","blockHeight":1471534,"blockHash":"0x6e27fe16eea91adfa509401cd2285714000af33c4b85741d2aafece45e1bce7e","stack":"AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  (0, assert_1.default)(val != null, msg)\n\n    at assertNotNull (/squid/util/util-internal/lib/misc.js:18:26)\n    at CallParser.next (/squid/substrate-ingest/lib/parse/call.js:324:50)\n    at CallParser.find (/squid/substrate-ingest/lib/parse/call.js:300:30)\n    at CallParser.visitWrapper (/squid/substrate-ingest/lib/parse/call.js:271:27)\n    at CallParser.visitCall (/squid/substrate-ingest/lib/parse/call.js:183:22)\n    at CallParser.visitBatchItems (/squid/substrate-ingest/lib/parse/call.js:242:22)\n    at CallParser.visitBatchAll (/squid/substrate-ingest/lib/parse/call.js:208:14)\n    at CallParser.visitCall (/squid/substrate-ingest/lib/parse/call.js:168:22)\n    at CallParser.visitExtrinsic (/squid/substrate-ingest/lib/parse/call.js:134:22)\n    at new CallParser (/squid/substrate-ingest/lib/parse/call.js:124:18)"}}
```

**Comment by lumir-mrkva** [comment]
works with latest image
